const {chromium} = require('C:/Users/LENOVO/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const output = __dirname;
const phase = process.argv[2] || 'before';
const api = 'http://127.0.0.1:8020';
const password = 'Local-ui-QA-2026!';
const email = `ui-${phase}-${crypto.randomUUID()}@example.test`;
let liveBrowser, livePage;
async function call(method, route, body, token) {
  const response = await fetch(api + route, {method, headers:{'Content-Type':'application/json', ...(token ? {Authorization:'Bearer '+token}: {})}, body: body ? JSON.stringify(body) : undefined});
  if (!response.ok) throw new Error(`${method} ${route}: ${response.status}`);
  return response.json();
}
(async()=>{
  const user = await call('POST','/auth/register',{email,name:'QA giao diện local',password,confirmation:password});
  const labels = [];
  for(let i=0;i<16;i++) {
    const id=crypto.randomUUID(); labels.push(id);
    await call('POST','/labels/sync',{op_id:crypto.randomUUID(),label_id:id,base_revision:0,kind:'upsert',name:['Học tập','Dự án','Ý tưởng','Công việc','Cá nhân','Lập kế hoạch','Ghi chú có tên nhãn rất dài để kiểm tra responsive'][i] || `Chủ đề ${i+1}`},user.token);
  }
  const ids=[];
  for(let i=0;i<9;i++) {
    let id;
    const target=[0,5,1,2,0,5,1,4,3][i];
    do { id=crypto.randomUUID(); } while (([...id].reduce((hash,c)=>(hash*31+c.charCodeAt(0))&0x7fffffff,0)%6)!==target || (i===0&&!id.startsWith('f')) || (i===1&&!id.startsWith('0')));
    ids.push(id);
    await call('POST','/sync',{op_id:crypto.randomUUID(),note_id:id,base_revision:0,kind:'upsert',title:['Kế hoạch học tập trong tuần','Thiết kế NoteTogether','Những ý tưởng cần ghi nhớ','Ghi chú bảo vệ riêng tư'][i] || `Ghi chú QA ${i+1}`,content:'## Mục tiêu\nPhân tách tiêu đề, nội dung và thông tin ghi chú để dễ đọc.\n- [ ] Hoàn thành phần giao diện\n- [x] Giữ bản nháp an toàn\n'+('Nội dung kiểm tra responsive. '.repeat(20)),labels:i===3?[]:[labels[i%3]],labels_format:'ids',pinned_at:i<2?'2026-10-09T02:00:00Z':null},user.token);
  }
  await call('POST',`/notes/${ids[3]}/protection`,{password:'QA-note-password!',confirmation:'QA-note-password!'},user.token);
  const browser=await chromium.launch({channel:'chrome',headless:true});
  liveBrowser=browser;
  const context=await browser.newContext({viewport:{width:1440,height:960},deviceScaleFactor:1});
  const page=await context.newPage(); const errors=[],warnings=[];
  livePage=page;
  page.on('pageerror',error=>errors.push(String(error)));
  page.on('console',message=>{if(message.type()==='error')errors.push(message.text());if(message.type()==='warning')warnings.push(message.text())});
  await page.goto('http://127.0.0.1:7357');
  await page.locator('flt-glass-pane').waitFor({state:'attached'});
  await page.waitForTimeout(1200);
  await page.evaluate(()=>document.querySelector('flt-semantics-placeholder')?.click());
  await page.getByRole('textbox',{name:'Email',exact:true}).waitFor({timeout:30000});
  await page.screenshot({path:path.join(output,`dashboard-${phase}-auth.png`)});
  await page.getByRole('textbox',{name:'Email',exact:true}).fill(email);
  await page.getByRole('textbox',{name:'Mật khẩu',exact:true}).fill(password);
  await page.getByRole('button',{name:'Đăng nhập',exact:true}).click();
  await page.getByText('Ghi chú của bạn',{exact:true}).waitFor();
  await page.waitForTimeout(1300);
  await page.screenshot({path:path.join(output,`dashboard-${phase}-desktop.png`)});
  await page.setViewportSize({width:1536,height:1024});
  await page.waitForTimeout(500);
  await page.screenshot({path:path.join(output,'dashboard-after-native.png')});
  await page.setViewportSize({width:390,height:844});
  await page.waitForTimeout(600);
  await page.screenshot({path:path.join(output,`dashboard-${phase}-mobile.png`)});
  const interactions=[];
  if (phase === 'after') {
    await page.getByRole('button',{name:'Bộ lọc nhãn',exact:true}).click();
    await page.getByRole('textbox',{name:'Tìm nhãn',exact:true}).fill('Học tập');
    await page.getByRole('checkbox',{name:'Học tập',exact:true}).click();
    await page.waitForTimeout(300);
    await page.screenshot({path:path.join(output,'dashboard-after-label-filter.png')});
    await page.getByRole('button',{name:/Áp dụng/}).click();
    await page.getByText('2 ghi chú',{exact:true}).waitFor();
    interactions.push('Label search/apply -> 2 matching notes');
    await page.getByRole('button',{name:'Bỏ bộ lọc nhãn',exact:true}).click();
    await page.getByRole('textbox',{name:'Tìm ghi chú',exact:true}).fill('Không có ghi chú này');
    await page.waitForTimeout(400);
    await page.mouse.move(200,480);
    await page.mouse.wheel(0,450);
    await page.getByText('Không tìm thấy ghi chú phù hợp',{exact:true}).waitFor();
    await page.mouse.wheel(0,-900);
    await page.waitForTimeout(400);
    await page.getByRole('button',{name:'Xóa tìm kiếm',exact:true}).click();
    await page.getByText('9 ghi chú',{exact:true}).waitFor();
    interactions.push('Live search -> empty state -> clear -> 9 notes');
    await page.getByRole('button',{name:'Danh sách',exact:true}).click();
    await page.waitForTimeout(500);
    await page.screenshot({path:path.join(output,'dashboard-after-list.png')});
    await page.mouse.move(200,480);
    await page.mouse.wheel(0,400);
    await page.waitForTimeout(400);
    fs.writeFileSync(path.join(output,'dashboard-card-dom.json'),JSON.stringify(await page.locator('flt-semantics').evaluateAll(nodes=>nodes.map(n=>({role:n.getAttribute('role'),label:n.getAttribute('aria-label'),text:n.textContent,rect:{x:n.getBoundingClientRect().x,y:n.getBoundingClientRect().y,width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height}}))),null,2));
    await page.getByLabel(/Kế hoạch học tập trong tuần/).click();
    await page.mouse.move(200,650);
    await page.mouse.wheel(0,400);
    await page.waitForTimeout(400);
    await page.getByRole('textbox',{name:'Nội dung',exact:true}).waitFor();
    const newContent='## Nội dung đã sửa\nBản nháp UI QA được đồng bộ bằng API thật.\n- [ ] Kiểm tra bố cục';
    await page.getByRole('textbox',{name:'Nội dung',exact:true}).click();
    await page.keyboard.press('Control+A');
    await page.keyboard.insertText(newContent);
    await page.waitForTimeout(1300);
    await page.mouse.wheel(0,-1000);
    await page.waitForTimeout(400);
    fs.writeFileSync(path.join(output,'dashboard-editor-dom.json'),JSON.stringify(await page.locator('flt-semantics').evaluateAll(nodes=>nodes.map(n=>({role:n.getAttribute('role'),label:n.getAttribute('aria-label'),text:n.textContent}))),null,2));
    let row;
    for(let attempt=0;attempt<20;attempt++) {
      row=await call('GET',`/notes/${ids[0]}`,null,user.token);
      if(row.content===newContent) break;
      await page.waitForTimeout(250);
    }
    if(row.content!==newContent)throw new Error('Editor content not acknowledged by API');
    interactions.push('Mobile editor -> type -> autosave -> GET content matches');
    await page.setViewportSize({width:1280,height:900});
    await page.getByRole('button',{name:'Đổi giao diện',exact:true}).click();
    const field=page.getByRole('textbox',{name:'Nội dung',exact:true});
    if(await field.inputValue()!==newContent)throw new Error('Editor lost text after resize/theme');
    await page.waitForTimeout(500);
    await page.screenshot({path:path.join(output,'dashboard-after-editor-dark.png')});
    interactions.push('Resize 390 -> 1280 + dark theme retains editor text');
    await page.getByRole('button',{name:'Quay lại',exact:true}).click();
    await page.waitForTimeout(500);
    await page.mouse.move(700,450);
    await page.mouse.wheel(0,-1500);
    await page.waitForTimeout(500);
    await page.getByText('Ghi chú của bạn',{exact:true}).waitFor();
    await page.getByRole('button',{name:'Lưới',exact:true}).click();
    await page.waitForTimeout(400);
    await page.screenshot({path:path.join(output,'dashboard-after-desktop-dark.png')});
    await page.setViewportSize({width:768,height:1024});
    await page.waitForTimeout(500);
    await page.screenshot({path:path.join(output,'dashboard-after-tablet-dark.png')});
    await page.setViewportSize({width:844,height:390});
    await page.waitForTimeout(500);
    await page.screenshot({path:path.join(output,'dashboard-after-landscape.png')});
    interactions.push('Tablet/short landscape renders and Home refreshes after return');
  }
  if(page.url()!=='http://127.0.0.1:7357/' || await page.title()!=='NoteTogether')throw new Error('Wrong page identity');
  if(errors.length)throw new Error(`Browser errors: ${errors.join('; ')}`);
  fs.writeFileSync(path.join(output,`dashboard-${phase}-qa.json`),JSON.stringify({date:new Date().toISOString(),phase,url:page.url(),title:await page.title(),viewports:['1440x960','1536x1024','390x844',...(phase==='after'?['1280x900','768x1024','844x390']:[])],notes:ids.length,labels:labels.length,errors,warnings,interactions},null,2));
  console.log(JSON.stringify({phase,title:await page.title(),errors,interactions}));
  await browser.close();
})().catch(async error=>{
  if(livePage) await livePage.screenshot({path:path.join(output,`dashboard-${phase}-failure.png`)}).catch(()=>{});
  if(liveBrowser) await liveBrowser.close().catch(()=>{});
  console.error(error);process.exit(1);
});
