const {chromium} = require('C:/Users/LENOVO/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict');
const out=__dirname,api='http://127.0.0.1:8023',url='http://127.0.0.1:7361';
const password='Word-fixture-2026!',email=`word-${crypto.randomUUID()}@example.test`;
let browser,page,uiToken; const errors=[],warnings=[],steps=[],shots=[];
async function call(method,route,body,token,expected){const r=await fetch(api+route,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});if(expected!==undefined)assert.equal(r.status,expected,`${method} ${route}`);else assert(r.ok,`${method} ${route}: ${r.status}`);return r.json();}
async function tap(loc){await loc.waitFor({state:'visible'});await page.waitForTimeout(180);const b=await loc.boundingBox();assert(b);await page.mouse.click(b.x+b.width/2,b.y+b.height/2);}
async function button(name){const escaped=name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');await tap(page.getByRole('button',{name:new RegExp('^'+escaped+'(?:\\s|$)')}));}
async function shot(name){await page.waitForTimeout(400);await page.screenshot({path:path.join(out,name+'.png')});shots.push(name+'.png');}
async function mark(name,fn){await fn();steps.push(name);console.log('PASS '+name);}
function plain(content){if(!content.startsWith('NTDOC1:'))return content;return JSON.parse(content.slice(7)).map(op=>op.insert).join('').slice(0,-1);}
(async()=>{
 const owner=await call('POST','/auth/register',{email,name:'QA Word local',password,confirmation:password});
 const editor=await call('POST','/auth/register',{email:`editor-${crypto.randomUUID()}@example.test`,name:'Editor',password,confirmation:password});
 const viewer=await call('POST','/auth/register',{email:`viewer-${crypto.randomUUID()}@example.test`,name:'Viewer',password,confirmation:password});
 const stranger=await call('POST','/auth/register',{email:`stranger-${crypto.randomUUID()}@example.test`,name:'Stranger',password,confirmation:password});
 const noteId=crypto.randomUUID(),locked=crypto.randomUUID();
 const content='## Mục tiêu\nTập trung vào những việc quan trọng và giữ ý tưởng trong một nơi.\n\n## Kế hoạch tuần\n- Ôn tập nội dung trên lớp\n- Hoàn thiện dự án NoteTogether\n- Dành thời gian đọc và ghi chú\n\n## Việc cần làm\n- [x] Rà soát giao diện trên PC\n- [ ] Kiểm tra trải nghiệm trên điện thoại';
 const rich='NTDOC1:'+JSON.stringify([{insert:'Nội dung bí mật ',attributes:{bold:true}},{insert:'được định dạng trực tiếp.\n'}]);
 for(const [id,title,text] of [[noteId,'Kế hoạch học tập trong tuần',content],[locked,'PRIVATE Word locked fixture',rich]])await call('POST','/sync',{op_id:crypto.randomUUID(),note_id:id,base_revision:0,kind:'upsert',title,content:text,labels:[]},owner.token);
 await call('POST',`/notes/${noteId}/shares`,{email:editor.user.email,role:'editor'},owner.token);
 await call('POST',`/notes/${noteId}/shares`,{email:viewer.user.email,role:'viewer'},owner.token);
 await call('POST',`/notes/${locked}/protection`,{password:'Word-note-2026!',confirmation:'Word-note-2026!'},owner.token);
 browser=await chromium.launch({channel:'chrome',headless:true});
 const context=await browser.newContext({viewport:{width:1536,height:1024},deviceScaleFactor:1});page=await context.newPage();page.setDefaultTimeout(15000);
 page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());if(m.type()==='warning')warnings.push(m.text());});
 await page.goto(url);await page.locator('flt-glass-pane').waitFor({state:'attached'});await page.waitForTimeout(1000);await page.evaluate(()=>document.querySelector('flt-semantics-placeholder')?.click());
 await page.getByRole('textbox',{name:'Email',exact:true}).waitFor({timeout:30000});await page.getByRole('textbox',{name:'Email',exact:true}).fill(email);await page.getByRole('textbox',{name:'Mật khẩu',exact:true}).fill(password);const loginResponse=page.waitForResponse(r=>r.url().endsWith('/auth/login')&&r.request().method()==='POST');await button('Đăng nhập');uiToken=(await (await loginResponse).json()).token;await page.getByText('Ghi chú của bạn',{exact:true}).waitFor();await page.waitForTimeout(800);
 await mark('Legacy document opens styled without migration write',async()=>{await tap(page.getByRole('group',{name:/Đã chia sẻ cho 2 người Kế hoạch học tập trong tuần/}));await page.waitForTimeout(1000);assert.equal((await call('GET',`/notes/${noteId}`,undefined,owner.token)).content,content);await shot('desktop-light');fs.writeFileSync(path.join(out,'editor-dom.txt'),await page.locator('body').ariaSnapshot());});
 // The probe also uses the same production binary and real authenticated API.
 if(process.env.QA_PROBE==='1'){console.log('PROBE '+noteId);await browser.close();return;}
 const field=page.getByRole('textbox',{name:'Nội dung',exact:true});

 await mark('Actual keyboard input, toolbar bold, durable server formatting',async()=>{
  await tap(field);await page.keyboard.press('Control+A');await page.keyboard.insertText('Tài liệu hiện đại\nNội dung dễ đọc và chỉnh sửa.\nViệc cần làm');await page.waitForTimeout(250);await page.keyboard.press('Control+Home');await page.keyboard.down('Shift');await page.keyboard.press('End');await page.keyboard.up('Shift');await button('In đậm (Ctrl+B)');await page.waitForTimeout(1400);
  const detail=await call('GET',`/notes/${noteId}`,undefined,owner.token);assert(detail.content.startsWith('NTDOC1:'));assert(plain(detail.content).includes('Tài liệu hiện đại'));assert(JSON.parse(detail.content.slice(7)).some(op=>op.attributes?.bold===true));
 });
 await mark('Heading and outline navigation',async()=>{await button('Kiểu đoạn văn');await tap(page.getByRole('menuitem',{name:'Tiêu đề 2',exact:true}));await page.waitForTimeout(1000);await shot('desktop-formatted');assert((await page.locator('body').ariaSnapshot()).includes('Mục lục'));});
 await mark('Visible text find and replace, save and reload formatting',async()=>{await page.getByRole('textbox',{name:'Nội dung',exact:true}).focus();await page.keyboard.press('Control+f');await page.getByRole('textbox',{name:'Tìm trong ghi chú',exact:true}).fill('hiện đại');await page.getByRole('textbox',{name:'Thay bằng',exact:true}).fill('sáng tạo');await button('Thay tất cả');await button('Đóng');await page.waitForTimeout(1400);const detail=await call('GET',`/notes/${noteId}`,undefined,owner.token);assert(plain(detail.content).includes('sáng tạo'));assert(JSON.parse(detail.content.slice(7)).some(op=>op.attributes?.bold));
  await page.reload();await page.locator('flt-glass-pane').waitFor({state:'attached'});await page.waitForTimeout(1000);await page.evaluate(()=>document.querySelector('flt-semantics-placeholder')?.click());await page.getByText('Ghi chú của bạn',{exact:true}).waitFor();await tap(page.getByRole('group',{name:/Đã chia sẻ cho 2 người Kế hoạch học tập trong tuần/}));await page.getByRole('textbox',{name:'Nội dung',exact:true}).waitFor();await page.waitForTimeout(500);assert((await page.locator('body').ariaSnapshot()).includes('sáng tạo'));await shot('desktop-reloaded');});
 await mark('Responsive, theme and focus retain the same document',async()=>{await button('Phóng to tài liệu');await button('Chế độ đọc');await shot('desktop-reading');await button('Tiếp tục soạn thảo');await button('Đổi giao diện');await shot('desktop-dark');for(const [width,height,name]of [[1000,800,'desktop-1000-dark'],[768,1024,'tablet-dark'],[390,844,'mobile-dark'],[844,390,'landscape-dark']]){await page.setViewportSize({width,height});await shot(name);await page.getByRole('textbox',{name:'Nội dung',exact:true}).focus();await page.waitForTimeout(250);assert((await page.getByRole('textbox',{name:'Nội dung',exact:true}).inputValue()).includes('sáng tạo'));}await page.setViewportSize({width:390,height:844});await button('Công cụ ghi chú');await tap(page.getByRole('menuitem',{name:'Đổi giao diện',exact:true}));await shot('mobile-light');await button('Viết tập trung');await shot('mobile-focus');await button('Thoát tập trung');await page.setViewportSize({width:1536,height:1024});});
 await mark('Viewer cannot mutate, editor writes using CAS, stranger denied',async()=>{const detail=await call('GET',`/notes/${noteId}`,undefined,owner.token);await call('GET',`/notes/${noteId}`,undefined,viewer.token);await call('GET',`/notes/${noteId}`,undefined,stranger.token,404);const operation={op_id:crypto.randomUUID(),note_id:noteId,base_revision:detail.revision,kind:'upsert',title:detail.title,content:detail.content,labels:detail.labels,labels_format:'ids'};await call('POST','/sync',operation,viewer.token,403);await call('POST','/sync',operation,editor.token);});
 await button('Quay lại');await page.getByText('Ghi chú của bạn',{exact:true}).waitFor();
 await mark('Rich cards and search exclude format metadata',async()=>{const search=page.getByRole('textbox',{name:/^Tìm ghi chú(?:\s|$)/});await search.fill('sáng tạo');await page.waitForTimeout(400);assert((await page.locator('body').ariaSnapshot()).includes('Kế hoạch học tập'));await search.fill('attributes');await page.waitForTimeout(400);assert(!(await page.locator('body').ariaSnapshot()).includes('Kế hoạch học tập'));await search.fill('');});
 await mark('Protected rich reader, actual editing and relock redaction',async()=>{await tap(page.getByRole('button',{name:/^Ghi chú đã khóa/}));await page.getByRole('textbox',{name:'Mật khẩu ghi chú',exact:true}).fill('Word-note-2026!');await button('Mở khóa');await page.getByRole('button',{name:'Chỉnh sửa',exact:true}).waitFor();await shot('protected-reader');await button('Chỉnh sửa');await tap(page.getByRole('textbox',{name:'Nội dung',exact:true}));await page.keyboard.press('Control+End');await page.keyboard.insertText(' Đã kiểm tra lưu an toàn.');await page.waitForTimeout(1500);assert(plain((await call('GET',`/notes/${locked}`,undefined,uiToken)).content).includes('Đã kiểm tra'));await shot('protected-editor');await button('Khóa lại');await page.getByRole('textbox',{name:'Mật khẩu ghi chú',exact:true}).waitFor();const dom=await page.locator('body').ariaSnapshot();assert(!dom.includes('PRIVATE Word locked fixture'));assert(!dom.includes('Nội dung bí mật'));await shot('protected-relocked');});
 const result={date_utc:new Date().toISOString(),browser:await browser.version(),target:url,base_commit:'717f0ab6b04b6f63ad7f921a82b91cd2f4b41319',working_tree:true,steps,shots,errors,warnings,viewports:['1536x1024','1000x800','768x1024','390x844','844x390'],browser_plugin:'Absent; bundled Playwright fallback',ai:'Fixture only; no live provider call',native_runtime:'NOT RUN',fps:'NOT RUN'};
 fs.writeFileSync(path.join(out,'qa.json'),JSON.stringify(result,null,2));assert.equal(errors.length,0);console.log(JSON.stringify(result));await browser.close();
})().catch(async e=>{console.error(String(e));if(page){await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});fs.writeFileSync(path.join(out,'failure-dom.txt'),await page.locator('body').ariaSnapshot().catch(()=>''));}fs.writeFileSync(path.join(out,'partial.json'),JSON.stringify({steps,shots,errors,warnings,error:String(e)},null,2));if(browser)await browser.close();process.exitCode=1;});
